services:
  postgres:
    container_name: postgres-17-postgis-3
    image: postgis/postgis:17-3.5
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
        - pgdata:/data/postgres
    logging:
      options:
        max-size: "200m"
        max-file: "7"
    networks:
      - inema

networks:
  inema:
    driver: bridge
    external: true

volumes:
  pgdata:
    driver: local
